---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
