# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KSr0ofXErVaacJW9WEBgINiZMXC7Ew==,iv:+mIKlz3m/yRJRCFRD4CzQJTV1xKte9mZnRbQ3geNBB4=,tag:HXEzQZ5fH7PVD7dArxDrjg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2N7scIIRU+FNzjtprBtg4iOVt13lGyY5jDYtAE4E3EnyLv40Yg==,iv:qPP10Xd915yHdLCyULbr9fZVazrlZjGzR5q2aaIr0u0=,tag:MWjagUya/YlMzkriw0EZfg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7aBPc56hdSVk/howhL8yHtIwEUE=,iv:nYkFt4sod+YdlMfPdQ6gG2KQw2/k8ruRYaKPeq1Bolg=,tag:hXY8HNu1TkTbUBTlwCCbLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjdk0c72a5mgy0m3yqyw2xuugar5gkf4vf56rrkhfzcgwen87vrsaysl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bllvaGpOTSsyelRMSVZ2
            aFlHN2pnMEdlNE9aMWZ3TkpKTGtHUFVGVzJVCkp2alkyUzk2NDl6eDkxS0VydzlC
            K2p5ZDR2MG9pNm5Kd29HT0dUekpwMnMKLS0tIFRvVEZqTERtSHpqWmd0U2NIampV
            ZnFjUjR5ZzhqQjBnRHVwYkdqckpteGsK5VcOx7syqWk//WuJKwqhyBwpoaIfzVEU
            BcZXSbCEU5IaWDIrOLpmnXSnHaTZxj2sc03+O7PIJpTnISx/WvCimA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T19:53:44Z"
    mac: ENC[AES256_GCM,data:n1K2c6msAwJmFf+2MCz9S+4eGJeVvwn2ySq3CENZykZlHsYYMuZpQKFzOXVt1cAYN0O+DXarddRVWbCj2gyML7q+mNGK9fI6ldgy4qBvhy6wvaCXaKtZfVQlTSZC5ox10OzFUi+Nh5pZsulCGJHhldfaprzTK31tUDERe6zacrg=,iv:UknFHWaIZP2iHh4n3nlovYNe+1e0uf0CZCVUoCygvfw=,tag:bU+0QRT7CNJfYMl7pCh6Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
