---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent-exporter
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    global:
      nameOverride: *app
    image:
      repository: docker.io/esanchezm/prometheus-qbittorrent-exporter
      tag: v1.2.0
    env:
      TZ: "${TIMEZONE}"
      EXPORTER_PORT: "7373"
      QBITTORRENT_HOST: "http://qbittorrent.media.svc.cluster.local:8080"
    service:
      main:
        ports:
          http:
            port: 7373
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 250Mi
