---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: qbittorrent-exporter
  namespace: media
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: qbittorrent.rules
      rules:
        - alert: qBittorrentExporterAbsent
          annotations:
            summary: The exporter for qBittorrent has disappeared from Prometheus
              service discovery
          expr: |
            absent(up{job="qbittorrent-exporter"} == 1)
          for: 30m
          labels:
            severity: critical
        - alert: qBittorrentDown
          annotations:
            summary: The qBittorrent application is down or metrics are not
              being collected
          expr: |
            qbittorrent_up{job="qbittorrent-exporter"} == 0
          for: 30m
          labels:
            severity: critical
