---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tautulli
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/tautulli
      tag: v2.9.7
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chart-box"
          hajimari.io/appName: "tautulli"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-only@kubernetescrd ,networking-traefik-sso@kubernetescrd
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "tautulli.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "tautulli-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 1000
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-v1
#      backup:
#        enabled: true
#        type: custom
#        volumeSpec:
#          nfs:
#            server: "expanse.${SECRET_PRIVATE_DOMAIN}"
#            path: /tycho/Apps/External/Backups/tautulli
#        mountPath: /config/backups
#        readOnly: false
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi
