# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k24Tv0YbiwVXlVEElFDp,iv:0Yz8tsPaGde6dnAIYHr2SjI7UsjgQKuKPvJq5Ueg2G0=,tag:Xa6w1QZke5dhun2wMi4h3A==,type:str]
    SECRET_MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:C4N51s/Q8HqMslpg2nESNg==,iv:vWR/BcWAS+efYXhdRsu9Ww3vuVSo6Z9QkTgPZwb4e34=,tag:79IPGKi9uo1/5cqYagrM/g==,type:str]
    SECRET_MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SzlzBjoRw62qLiPrQMCBsPRbm+uwdUTY29LzPdhl5+k=,iv:hVSjXRlYzcCh6rnhEzxgGhvBwsU87N6JMYNN2+nnR28=,tag:YBuLKO5VUlxj4yU4S+8Qbw==,type:str]
    SECRET_PLEX_CLAIM: ENC[AES256_GCM,data:vPWZhRU+EnIoyUTeMpLNwGyE1yFyoGaKaRg=,iv:m0W7zfNiFXnJzHbaxpo2P8/KyJiOVXvuBu+xzOlruFA=,tag:lyCZqSruPp2iR9czxfZO5g==,type:str]
    SECRET_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:uxm00NfI13CAMg==,iv:HMe2+SfTe4gNo8B1x7h7oa3HA87nLxh4rVZSMFmBXGQ=,tag:IFYuztKrGnPLJGy4YzTaNg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I0GjdTjEdM2AOJxY+hI1Fu6914/m9A==,iv:UnlrMIUJQV+fm79NtNswj1ou38kzgXiVPh9UrZ9vrbY=,tag:M+xFy0Qo2i9DR6aEeiRWEw==,type:str]
    SECRET_CODE_SERVER_PASSWORD: ENC[AES256_GCM,data:+1+NovDobs4lNIfp3TI=,iv:STNbQsUtHRLJwxbUzt3mhwG8+coFxeC7rQc2fgcc7kg=,tag:vybax0aIK1N9y62KUSZNeA==,type:str]
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:+q9npTj2qMu0AKUkPOQPMZoS4YTEG21qK62xzBQv,iv:GcnWUmLoSHfMiybwxbVFjL+aFPwcS87FvMQEAbOV2EM=,tag:Gex7YOa5ckUmvWMhZtxjwA==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:hGovIoHMedzC6czha4N3KC/x/ozkxWz67Av5r/kU,iv:NB0NpYiQCn9fhAq8/GnQEJGN61s9JNRDaQ6DMfsVuwc=,tag:B31q2AToTowrQVGicu7cKA==,type:str]
    SECRET_TRAEFIK_AUTH_HOST: ENC[AES256_GCM,data:NCdHyPbIzzLM/XFGXgxopo6Jw3zp,iv:JL0cdjFQgRuT3N3pPExSqcIx1qU6wTOkY3Hy+qY3gZo=,tag:2goMYj2UkwrZoZoxooYe4Q==,type:str]
    SECRET_TRAEFIK_AUTH_SECRET: ENC[AES256_GCM,data:ytPT3jLqdCBVxff2HOwOBCVJG9rDPGkhouc/GFfTrs/+6HndI/bkwxHN/gylmjeZqtXxOWG8dNWbSxsiHWQVEw==,iv:G0/rthPMi/6pgL24fngwvGFO8Sm829qgDMPZ5m+wKb4=,tag:UTaGMtWVFieY+glGT5pDmg==,type:str]
    SECRET_TRAEFIK_AUTH_URL_PATH: ENC[AES256_GCM,data:qFk3hNFi2dM0c3qGoq77ZA8/WqUk56C+pvWpqEGFZLA/+pqF,iv:osc9337Jfar5njvgSOXGfJ5KK0+YLXH5xUhrIjWQjLA=,tag:RVRAbwe9AxfDOSJxBUIwUg==,type:str]
    SECRET_TRAEFIK_AUTH_WHITELIST: ENC[AES256_GCM,data:yZnvC6nAUDvBbg2H2XPV4oKpnRLljw==,iv:PzmW2+1X7WkVKMRPRKmIrPZSvOHeOhtAr6UFm9AxTWM=,tag:ktsRb2mSr31MX712gdqR0g==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:jeL/fwqSTZXQho0KGtNFO9RtbOCj9LSM4jBqM2FFY1ZZg8zmkRrWWiA3+pDI+RJLK9UNAkKjZhKPwNTuYee/iaV3f3LzApRZ3Q==,iv:45r+Ficw8w9kARx2c8rVC8S76JORMPHPVeQ9JpkDtEc=,tag:kkQtlcuT2xsDM4AA9ATCRQ==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:1ytLOpmQfSGep3zRs4MGBS5mPmhwc8RVY/6JK9DuhMg9hIg=,iv:QmmRJbsLJYv7UxIhzMGdv2EfJGXMsUv6IPW+bxdqzBk=,tag:xg6Xg7f858y4VMypzprG7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjdk0c72a5mgy0m3yqyw2xuugar5gkf4vf56rrkhfzcgwen87vrsaysl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpalhjcWFVZHBHT2FuRGFU
            SHpMeW45YUhJZVZ4b2pSNW9xdzg1VFN3NDBRCm9EUlpEd1k1SnR1VjE1OHIxTGxv
            bHdQYUI3M0xqcHFORWkyM0F2c08xL0UKLS0tIGowRkJtZlo5RExXczhxY2J5NlF3
            R3ZGcG9oUFZubEg0MVlNemFSQTdyTXcKhJtkUPO7v8N97/tvJlnW9U/DNamYE4kr
            NW+K/0sEnQHcZ0s/yXvS7/vhSD/ID2y1yASmjDuEvU93rPZFfdkyZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-03T20:32:50Z"
    mac: ENC[AES256_GCM,data:fIZOu6W2Xhp2PZ4bnJg3S6C60ZCgg6QFBfGee5m01Pljn2DbkE4vWSTYgnR/mQXUj7uMNLR86QmiTKc/ULPVrfniBO4Q5t543hQbOHDkXnXLqcGZFngfn5n8LBvQIeRloOrw6orIDympt/zUgY02a6lA6KZFam6O01vFzk8Hhg0=,iv:GEn3AmgFHNtrXomkKnrn3Lo/+A/+abcA6OZtz7qkVus=,tag:kx9Z78gN8kVRMT8apIKHig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
