---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: navidrome
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    image:
      repository: deluan/navidrome
      pullPolicy: IfNotPresent
      tag: 0.47.5

    env:
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music-collection
      ND_SCANINTERVAL: 15m
      ND_DEFAULTTHEME: Spotify-ish
      ND_ENABLEGRAVATAR: true
      ND_SESSIONTIMEOUT: 24h
      ND_ENABLEDOWNLOADS: false
      ND_ENABLEFAVOURITES: true
      ND_ENABLETRANSCODINGCONFIG: "true"
    persistence:
      config:
        enabled: true
        mountPath: /data
        existingClaim: navidrome-config
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /media/collections/music
        mountPath: /music-collection

    service:
      main:
        annotations:
          # prometheus.io/probe: "true"
          # prometheus.io/protocol: http

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
          hajimari.io/appName: "navidrome"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: "navidrome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "navidrome.${SECRET_DOMAIN}"
            secretName: "navidrome-tls"
