---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: unpackerr
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: docker.io/golift/unpackerr
      tag: 0.9.9
    env:
      TZ: "${TIMEZONE}"
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_PATHS_0: /media/downloads/tv-sonarr
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_PATHS_0: /media/downloads/radarr
      UN_LIDARR_0_URL: http://lidarr:8686
      UN_LIDARR_0_PATHS_0: /media/downloads/lidarr
      UN_READARR_0_URL: http://readarr:8787
      UN_READARR_0_PATHS_0: /media/downloads/readarr
      # Prowlarr folder
      UN_FOLDER_0_PATH: /media/downloads/prowlarr
      UN_FOLDER_0_INTEVAL: 2s
      UN_FOLDER_0_EXTRACT_PATH: /media/misc
      UN_FOLDER_0_DELETE_AFTER: 0
    envFrom:
      - secretRef:
          name: unpackerr
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 1000
    persistence:
      config:
        enabled: false
      complete:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /media
        mountPath: /media
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
