# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-backups-secrets
    namespace: longhorn-system
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Rqax9R3ofZAG68xzTsXEmhtbVcGb47AnYg==,iv:x4cogC65pzojKvMLcMXXbABobABozLU38p2RcrBYAX8=,tag:F+NaXTd/jDqUlelK21r3RQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:t7o+oXwx0kSJ56JsziPfgg==,iv:JmoT0o1wz2pGDiqqPAaCHy7jngL4EkB+VJlYF4K4rOA=,tag:LuS7PaW95xneI5tx9d+FoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y8iqfL1p7Tu95JOTkvQmo0nhQlnyYuarPBJhg3+vhWI=,iv:1limPFJjSBMeVYucmYcCurnwS6jo/txBJztucmAneBA=,tag:Pycut7/OduIrW5cI7sldLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjdk0c72a5mgy0m3yqyw2xuugar5gkf4vf56rrkhfzcgwen87vrsaysl3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc0I5bW1LWXdHQzY5SE5T
            em03aVNwT25LUGcwY3Z1ZHpzbGtEU1FKb1JFCmFUeUFhN0tzaWgreVAvY2V0RThD
            Smt4QTc2SHg0bEZlQWRmc29keXJteUUKLS0tIFV4ZVV0eXVUNGZuR3NISXJYMDJB
            eUtJd1dmQlFoVFRXWVNnazRESXE4MVkKgW2JTqAbrgrHNo+WdSXJMg+r2gDVJRdy
            eMjUJBn5pV97W/0aVW3Ipd1h12SWbM4W1/uansPkStDiEcRkdAs8WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T15:46:34Z"
    mac: ENC[AES256_GCM,data:oWVCrCA6yb8KK3cTxYde/Vbc3xnK01S/IaoRtihuvF/dCkc5UpfO3l3CjupmiiprwktVEUxi4jMLJDYRPtSbqSqANruHZmQw+yuc4FWiw2gjMaDYYZOzFJWz+8xKD5udpLO8cEIsw7RrZlqY0mOSVQ+U5DIfLOem7mLyEnxxUeQ=,iv:3XMForxbTd1VIN6LxvRVvh24vfLT5QbVZdgNIgiamzY=,tag:smTDYGbnK6lJ1fgz3SwJPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
