---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lidarr
  - media-browser
  - navidrome
  - overseerr
  - plex
  - prowlarr
  - pyload
  - qbittorrent
  - radarr
  - readarr
  - sabnzbd
  - sonarr
  - tautulli
  - unpackerr
