apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-sso
  namespace: networking
  labels:
    app: traefik-sso
spec:
  selector:
    matchLabels:
      app: traefik-sso
  template:
    metadata:
      labels:
        name: traefik-sso
        app: traefik-sso
    spec:
      containers:
        - name: traefik-sso
          image: thomseddon/traefik-forward-auth:2-arm
          imagePullPolicy: Always
          env:
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              value: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID}"
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              value: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}"
            - name: SECRET
              value: "${SECRET_TRAEFIK_AUTH_SECRET}"
            - name: AUTH_HOST
              value: "${SECRET_TRAEFIK_AUTH_HOST}"
            - name: WHITELIST
              value: "${SECRET_TRAEFIK_AUTH_WHITELIST}"
            - name: COOKIE_DOMAIN
              value: "${SECRET_DOMAIN}"
            - name: INSECURE_COOKIE
              value: "true"
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 4181
