---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: "${TIMEZONE}"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - dev
          - kube-system
          - longhorn-system
          - media
          - monitoring
          - networking
      name: "Ilan"
      customApps:
        - name: Nas Server
          url: "http://${NAS_ADDR}"
          icon: nas
        - name: Nas Portainer
          url: "http://${NAS_ADDR}:${NAS_PORTAINER_PORT}"
          icon: nas
        - name: Nas S3 Buckets
          url: "http://${NAS_ADDR}:${NAS_MINIO_DASHBOARD_PORT}"
          icon: nas
        - name: Pi-Hole
          url: "http://${LOCAL_DNS_SERVER_ADDR}/admin"
          icon: pi-hole
      groups:
        - name: KWS Cluster
          links:
            - name: KWS GitOps
              url: "https://github.com/ilanKushnir/kws-cluster"
            - name: KWS Charts
              url: "https://github.com/ilanKushnir/kws-charts"
            - name: Medium post
              url: "https://medium.com/@ilankushnir/kws-cluster-e7e079cf103b"
        - name: Self Hosted
          links:
            - name: Awesome SH
              url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
            - name: K8S@Home Charts
              url: "https://github.com/k8s-at-home/charts/tree/master/charts"
            - name: Linuxserver
              url: "https://fleet.linuxserver.io/"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Box
              url: "https://box.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
            - name: Trash Guides
              url: "https://trash-guides.info/"
        - name: Reading
          links:
            - name: Instapaper
              url: "https://www.instapaper.com/u"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "apps-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-only@kubernetescrd
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
